#:schema node_modules/wrangler/config-schema.json

name = "hottospotbackend"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[vars]
NODE_VERSION = "20"

[[d1_databases]]
binding = "DB"
database_name = "hotto_spot_db"
database_id = "11ca95b9-71ca-4ff5-b16e-822f220d4f10"

[observability]
enabled = true
