#:schema node_modules/wrangler/config-schema.json

name = "hottospotbackend"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[vars]
NODE_VERSION = "20"

[[d1_databases]]
binding = "DB"
database_name = "hotto_spot_db"
database_id = "960cee2d-398d-4197-a8ee-d220eb5ce0b9"

[observability]
enabled = true
